# Generated by Django 3.2.3 on 2021-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=20)),
                ('nivel', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
