# Generated by Django 3.2.3 on 2021-08-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
