# Generated by Django 3.2.3 on 2021-08-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210807_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
        migrations.AddField(
            model_name='skill',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
    ]
