# Generated by Django 3.2.3 on 2021-08-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210807_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-nombre'], 'verbose_name_plural': 'Persona'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill'], 'verbose_name_plural': 'Skill'},
        ),
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='nivel',
            field=models.IntegerField(),
        ),
    ]
