# Generated by Django 3.2.3 on 2021-08-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210812_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
