# Generated by Django 3.2.3 on 2021-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_skill_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='persona/pdf'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
